secrets: secretfile.yml

templates:

  tv:
    include: series.yml
    content_filter:
      reject:
        - 'password.txt'
        - '*.wmv'
    # regexp:
    #  reject:
    #    - 'WEB-DL'

  transmission:
    transmission:
      enabled: yes
      host: https://hostname/transmission/rpc
      port: 9099
      ratio: 2
      username: '{{ secrets.transmission.username }}'
      password: '{{ secrets.transmission.password }}'

  sceneaccess-tv-rss:
    rss:
      url: 'https://sceneaccess.eu/rss?feed=dl&cat=27&passkey={{secrets.sceneaccess.rss_key}}'
    verify_ssl_certificates: no

  demonoid-tv-rss:
    rss:
      url: http://www.demonoid.pw/rss/3.xml
    verify_ssl_certificates: no

tasks:

  iptorrents-tv:
    template: [tv, transmission]
    discover:
      what:
        - emit_series: yes
      from:
        - iptorrents: 
            rss_key: '{{ secrets.iptorrents.rss_key }}'
            uid: 31337357
            password: '{{ secrets.iptorrents.password }}'
            category: 
              - TV-x264
              - TV-XVID 
    priority: 10

  kat-tv:
    verify_ssl_certificates: no
    template: [tv, transmission]
    discover:
      what:
        - emit_series: yes
      from:
        - kat:
            category: tv
    priority: 20

  demonoid-tv:
    template: [tv, transmission, demonoid-tv-rss]
    priority: 30

  sceneaccess-tv:
    template: [tv, transmission, sceneaccess-tv-rss]
    priority: 40

  completed-files:
    transmission_files:
      enabled: yes
      host: https://hostname/transmission/rpc
      port: 9099
      username: '{{ secrets.transmission.username }}'
      password: '{{ secrets.transmission.password }}'
    # Don't download anything we already have
    exists: 
      - '/Volumes/External/downloads/'
    regexp:
      # exclude junk files
      reject:
        - \.txt
        - \.nfo
        - sample
        - \.sfv
      from: title
    accept_all: yes
    exec:
      allow_background: yes
      auto_escape: no
      fail_entries: yes
      on_output:

        # launch scp in the background to pull files down locally
        mkdir -p "/Volumes/External/downloads/$(dirname '{{location}}')";
        scp uname@host:'{{location_full}}' '/Volumes/External/downloads/{{location}}';